# my global config
global:
  scrape_interval: 1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prom"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "broker"
    static_configs:
      - targets: ["pulsar1-eu:8080","pulsar2-eu:8080","pulsar1-us:8080","pulsar2-us:8080"]

  - job_name: "bookie"
    static_configs:
      - targets: ["bk1-eu:8000", "bk2-eu:8000", "bk1-us:8000", "bk2-us:8000"]

  - job_name: "zk"
    static_configs:
      - targets: ["zk:8000"]
